/**
 * Run before build to inline the auth background image so it loads with first paint.
 * Usage: node scripts/inline-auth-bg.js (from apps/web)
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const publicDir = path.join(root, "public");
const imagePath = path.join(publicDir, "strivonbackgroundimagedesktop.jpeg");
const outPath = path.join(root, "lib", "auth-bg-data.generated.ts");

let dataUrl = "";
try {
  const buf = fs.readFileSync(imagePath);
  dataUrl = "data:image/jpeg;base64," + buf.toString("base64");
  console.log("[inline-auth-bg] Inlined strivonbackgroundimagedesktop.jpeg");
} catch (e) {
  console.warn("[inline-auth-bg] Could not read image:", e.message);
}

const content = `// Generated by scripts/inline-auth-bg.js - do not edit
export const AUTH_BG_DATA_URL: string = ${JSON.stringify(dataUrl)};
`;

fs.writeFileSync(outPath, content, "utf8");
console.log("[inline-auth-bg] Wrote lib/auth-bg-data.generated.ts");
